#!/usr/bin/env python3
"""Write docs/01-capability-matrix.md from the radio capability files (backend/radio_remote/radio/capabilities/*.toml).

  python tools/gen_capability_doc.py            # rewrite the page
  python tools/gen_capability_doc.py --check    # exit 1 if the page is out of date (the tests run this)

The page is generated so it can never disagree with what the program really offers. The status of each function comes from the capability
file: false = not available, "unverified" = not offered yet, true = offered. For a radio that has been bench-tested (the FT-991A) the
comment on the line decides the wording: BENCH-VERIFIED / NOT bench-verified (see the header of ft991a.toml).
"""
from __future__ import annotations

import argparse
import re
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CAPS = ROOT / "backend" / "radio_remote" / "radio" / "capabilities"
OUT = ROOT / "docs" / "01-capability-matrix.md"
RADIOS = ["ft991a", "ftdx10", "ftdx101d", "ftdx101mp", "ft710"]

LABELS = {                                    # key -> (group, label)
    "ptt": ("Transmit", "PTT (hold to transmit)"), "tuner": ("Transmit", "Antenna tuner on/off"),
    "tuner_tune": ("Transmit", "TUNE (start the tuner: transmits a carrier)"), "processor": ("Transmit", "Speech processor"),
    "monitor": ("Transmit", "Monitor"), "mic_select": ("Transmit", "Microphone input (menu: MIC / REAR)"),
    "swr_meter": ("Meters", "SWR meter"), "alc_meter": ("Meters", "ALC meter"), "comp_meter": ("Meters", "Compression meter"),
    "ipo": ("Receiver", "IPO / preamp (AMP1, AMP2)"), "att": ("Receiver", "Attenuator (on/off)"),
    "att_levels": ("Receiver", "Attenuator (OFF / 6 / 12 / 18 dB)"), "agc": ("Receiver", "AGC (OFF / FAST / MID / SLOW / AUTO)"),
    "width": ("Receiver", "Filter width"), "if_shift": ("Receiver", "IF shift"), "contour": ("Receiver", "Contour"),
    "apf": ("Receiver", "Audio peak filter (CW)"), "manual_notch": ("Receiver", "Manual notch"), "auto_notch": ("Receiver", "Auto notch"),
    "dnr": ("Receiver", "Noise reduction (DNR)"), "noise_blanker": ("Receiver", "Noise blanker"),
    "rit": ("Receiver", "RIT"), "xit": ("Receiver", "XIT"),
    "vfo_b": ("VFOs and memories", "VFO B (A=B, B=A, swap, set frequency)"), "split": ("VFOs and memories", "Split"),
    "quick_split": ("VFOs and memories", "Quick split (QS)"), "memories": ("VFOs and memories", "Memory channels: list and recall"),
    "c4fm": ("Radio", "C4FM mode (mode select only)"), "dgid": ("Radio", "WIRES DG-ID menu value"),
    "vhf": ("Radio", "144 MHz band"), "uhf": ("Radio", "430 MHz band"),
    "power_off_cat": ("Radio", "Power off over CAT"), "power_on_cat": ("Radio", "Power on over CAT (from standby)"),
    "antenna_switching": ("Radio", "Antenna switching over CAT"),
}
GROUPS = ["Transmit", "Meters", "Receiver", "VFOs and memories", "Radio"]


def load(radio: str) -> tuple[dict, dict[str, str]]:
    """(parsed profile, {feature: inline comment})"""
    path = CAPS / f"{radio}.toml"
    data = tomllib.loads(path.read_text(encoding="utf-8"))
    comments, section = {}, ""
    for line in path.read_text(encoding="utf-8").splitlines():
        s = re.match(r"\s*\[([\w.]+)\]", line)
        if s:
            section = s.group(1)
            continue
        m = re.match(r"\s*([a-z0-9_]+)\s*=\s*[^#]*#\s*(.*)$", line)
        if m and section == "features":
            comments[m.group(1)] = m.group(2)
    return data, comments


def status(value, comment: str, tested: bool) -> str:
    if value is False:
        return "-"
    if value == "unverified":
        return "not offered yet"
    if not tested:
        return "from the manual"
    if "NOT bench-verified" in comment or "NOT yet" in comment:
        return "from the manual, untested"
    return "works"


def fmt_ranges(r: list) -> str:
    def mhz(hz): return f"{hz / 1e6:g}"
    return ", ".join(f"{mhz(a)}-{mhz(b)} MHz" for a, b in r)


def render() -> str:
    profiles = {r: load(r) for r in RADIOS}
    names = [profiles[r][0]["model"]["name"].replace("Yaesu ", "") for r in RADIOS]
    out = [
        "# What each radio supports",
        "",
        "<!-- Generated by tools/gen_capability_doc.py from backend/radio_remote/radio/capabilities/*.toml. Do not edit by hand. -->",
        "",
        "The **FT-991A** is complete and tested on a real radio. **FTDX10, FTDX101D, FTDX101MP and FT-710** are *experimental*: their profiles",
        "were written from the radios' CAT manuals and tested only against a simulator, and the page shows an \"experimental\" banner.",
        "See [other radios](08-other-radios.md) for what to check first if you have one.",
        "",
        "How to read the table:",
        "",
        "| Mark | Meaning |",
        "|---|---|",
        "| works | tested on the real FT-991A |",
        "| from the manual | implemented from the CAT manual, not yet tried on a real radio of that model |",
        "| from the manual, untested | on the FT-991A too, but not yet tried there |",
        "| not offered yet | exists in the manual but is switched off until it has been tried on the radio (it can transmit, or its table was wrong on another model) |",
        "| - | the radio does not have it, or it is not available over CAT |",
        "",
        "## Functions",
        "",
        "| Function | " + " | ".join(names) + " |",
        "|---|" + "---|" * len(RADIOS),
    ]
    keys = sorted({k for r in RADIOS for k in profiles[r][0]["features"]},
                  key=lambda k: (GROUPS.index(LABELS.get(k, ("Radio", k))[0]), LABELS.get(k, ("", k))[1].lower()))
    last = None
    for k in keys:
        group, label = LABELS.get(k, ("Radio", k))
        if group != last:
            out.append(f"| **{group}** |" + " |" * len(RADIOS))
            last = group
        cells = []
        for r in RADIOS:
            data, comments = profiles[r]
            cells.append(status(data["features"].get(k, False), comments.get(k, ""), bool(data["model"].get("bench_tested"))))
        out.append(f"| {label} | " + " | ".join(cells) + " |")
    out += ["", "## Modes, bands and frequency range", "", "| | " + " | ".join(names) + " |", "|---|" + "---|" * len(RADIOS)]
    out.append("| Modes | " + " | ".join(f"{len(profiles[r][0]['modes']['list'])}: " + ", ".join(profiles[r][0]["modes"]["list"]) for r in RADIOS) + " |")
    out.append("| Bands | " + " | ".join(", ".join(profiles[r][0]["bands"]["list"]) for r in RADIOS) + " |")
    out.append("| Frequency range | " + " | ".join(fmt_ranges(profiles[r][0]["frequency"]["ranges"]) for r in RADIOS) + " |")
    out.append("| CAT identity (`ID;`) | " + " | ".join(f"`ID{profiles[r][0]['model']['cat_id']};`" for r in RADIOS) + " |")
    out += ["", "## Levels", ""]
    lv = []
    for r in RADIOS:
        lv.append(", ".join(f"{v['label']} {v['min']}-{v['max']}" for v in profiles[r][0].get("levels", {}).values()))
    out += ["| | " + " | ".join(names) + " |", "|---|" + "---|" * len(RADIOS), "| Level controls | " + " | ".join(lv) + " |"]
    out += [
        "",
        "## Not available on any of them (over CAT)",
        "",
        "- **C4FM RX/TX DG-ID**: not reachable over CAT (checked on a real FT-991A: no menu value changes). Only the WIRES DG-ID menu value is read.",
        "- **Antenna selection**: the FT-991A has no CAT command for it.",
        "- **VOX** is deliberately not offered: VOX plus remote audio is a risk of unintended transmission.",
        "- **Memory writing**: the program reads and recalls memory channels but never creates, changes or deletes one.",
        "",
        "Where each status comes from: the capability files in `backend/radio_remote/radio/capabilities/`; the results of the real-radio tests are in",
        "[bench results](bench-results.md).",
        "",
    ]
    return "\n".join(out)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="do not write; exit 1 when the page is out of date")
    a = ap.parse_args(argv)
    text = render()
    if a.check:
        current = OUT.read_text(encoding="utf-8").replace("\r\n", "\n") if OUT.exists() else ""
        if current != text:
            print(f"{OUT} is out of date: run python tools/gen_capability_doc.py", file=sys.stderr)
            return 1
        return 0
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT} ({len(text.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
